//filtering by genre/subgenre

//actor lists

//sorting by rating or duration

const movies = [
  {
    id: 1,
    title: "Galactic Guardian",
    year: 2021,
    genre: "SF",
    subgenre: "Super Hero SF",
    rating: 7.8,
    duration: 128,
    posterUrl: "https://picsum.photos/300/450?random=1",
    actors: ["Jason North", "Lena Volkov", "Marcus Reed"],
  },
  {
    id: 2,
    title: "Photon Defender",
    year: 2020,
    genre: "SF",
    subgenre: "Super Hero SF",
    rating: 6.9,
    duration: 118,
    posterUrl: "https://picsum.photos/300/450?random=2",
    actors: ["Aaron Blake", "Sophie Turnerfield", "Ivan Petrov"],
  },
  {
    id: 3,
    title: "Nebula Knight",
    year: 2023,
    genre: "SF",
    subgenre: "Super Hero SF",
    rating: 8.1,
    duration: 134,
    posterUrl: "https://picsum.photos/300/450?random=3",
    actors: ["Daniel Cross", "Mila Hart", "Victor Kane"],
  },
  {
    id: 4,
    title: "Crystal Planet",
    year: 2019,
    genre: "SF",
    subgenre: "Fantazy SF",
    rating: 7.2,
    duration: 121,
    posterUrl: "https://picsum.photos/300/450?random=4",
    actors: ["Laura Finch", "Tom Alvarez", "Rina Kobayashi"],
  },
  {
    id: 5,
    title: "Astro Strike",
    year: 2018,
    genre: "SF",
    subgenre: "Action SF",
    rating: 7.5,
    duration: 115,
    posterUrl: "https://picsum.photos/300/450?random=5",
    actors: ["Chris Madden", "Olga Petrenko", "Samuel Wright"],
  },
  {
    id: 6,
    title: "London Extraction",
    year: 2020,
    genre: "Action",
    subgenre: "British Action",
    rating: 7.0,
    duration: 110,
    posterUrl: "https://picsum.photos/300/450?random=6",
    actors: ["Oliver Grant", "Henry Collins", "Emily Stone"],
  },
  {
    id: 7,
    title: "Highway Fury",
    year: 2021,
    genre: "Action",
    subgenre: "Car chase Action",
    rating: 6.8,
    duration: 104,
    posterUrl: "https://picsum.photos/300/450?random=7",
    actors: ["Tyler King", "Rosa Martinez", "Jake Hunter"],
  },
  {
    id: 8,
    title: "Cyber Assault",
    year: 2023,
    genre: "Action",
    subgenre: "SF Action",
    rating: 7.9,
    duration: 122,
    posterUrl: "https://picsum.photos/300/450?random=8",
    actors: ["Nathan Cole", "Eva Schmidt", "Alexei Morozov"],
  },
  {
    id: 9,
    title: "Dead City Rising",
    year: 2019,
    genre: "Horror",
    subgenre: "Zombie horror",
    rating: 6.7,
    duration: 101,
    posterUrl: "https://picsum.photos/300/450?random=9",
    actors: ["Hannah Brooks", "Logan Pierce", "David Kim"],
  },
  {
    id: 10,
    title: "Voices Behind the Wall",
    year: 2024,
    genre: "Horror",
    subgenre: "Psychological horror",
    rating: 8.0,
    duration: 109,
    posterUrl: "https://picsum.photos/300/450?random=10",
    actors: ["Natalie Ward", "Eric Foster", "Sofia Ivanova"],
  },
  {
    id: 11,
    title: "Haunted Party",
    year: 2018,
    genre: "Horror",
    subgenre: "Comedy horror",
    rating: 6.5,
    duration: 95,
    posterUrl: "https://picsum.photos/300/450?random=11",
    actors: ["Ben Carter", "Lucy Fields", "Tommy Drake"],
  },
  {
    id: 12,
    title: "Love Algorithm",
    year: 2021,
    genre: "Comedy",
    subgenre: "Romantic Comedy",
    rating: 7.3,
    duration: 102,
    posterUrl: "https://picsum.photos/300/450?random=12",
    actors: ["Liam Carter", "Anna Novak", "Grace Lee"],
  },
  {
    id: 13,
    title: "Funeral Laughs",
    year: 2019,
    genre: "Comedy",
    subgenre: "Black Comedy",
    rating: 7.1,
    duration: 97,
    posterUrl: "https://picsum.photos/300/450?random=13",
    actors: ["Peter Walsh", "Clara Gomez", "Sean O'Neil"],
  },
  {
    id: 14,
    title: "Election Circus",
    year: 2024,
    genre: "Comedy",
    subgenre: "Satiric Comedy",
    rating: 7.6,
    duration: 111,
    posterUrl: "https://picsum.photos/300/450?random=14",
    actors: ["Victor Lane", "Maria Costa", "Daniel Wright"],
  },
  {
    id: 15,
    title: "Autumn Letters",
    year: 2018,
    genre: "Drama",
    subgenre: "Melodrama",
    rating: 7.4,
    duration: 120,
    posterUrl: "https://picsum.photos/300/450?random=15",
    actors: ["Emma Laurent", "Julian Park", "Nina Petrova"],
  },
  {
    id: 16,
    title: "Sunday Table",
    year: 2022,
    genre: "Drama",
    subgenre: "Family Drama",
    rating: 7.7,
    duration: 113,
    posterUrl: "https://picsum.photos/300/450?random=16",
    actors: ["Michael Harris", "Laura Bennett", "Chris Doyle"],
  },
  {
    id: 17,
    title: "MI-Shadow",
    year: 2023,
    genre: "British",
    subgenre: "Action British",
    rating: 7.2,
    duration: 119,
    posterUrl: "https://picsum.photos/300/450?random=17",
    actors: ["Henry Black", "Oliver Shaw", "Kate Whitmore"],
  },
  {
    id: 18,
    title: "Tea Time Trouble",
    year: 2019,
    genre: "British",
    subgenre: "Cpmedy British",
    rating: 6.9,
    duration: 98,
    posterUrl: "https://picsum.photos/300/450?random=18",
    actors: ["George Baker", "Amelia Clarke", "Freddie Moore"],
  },
  {
    id: 19,
    title: "Ashes of the Battalion",
    year: 2021,
    genre: "Tragedy",
    subgenre: "War Tragedy",
    rating: 8.2,
    duration: 137,
    posterUrl: "https://picsum.photos/300/450?random=19",
    actors: ["Robert Hayes", "Daniel Novak", "Ivan Markovic"],
  },
  {
    id: 20,
    title: "Mindfall",
    year: 2024,
    genre: "Tragedy",
    subgenre: "Psychological Tragedy",
    rating: 8.0,
    duration: 124,
    posterUrl: "https://picsum.photos/300/450?random=20",
    actors: ["Elena Petrova", "Thomas Green", "Lucas Meyer"],
  },
];
